name: Create Release on tag push
on:
  push:
    tags:        
      - '*'
  workflow_dispatch: 


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log Build Information
        run: |
          echo "================================================"
          echo "Build job started for: ${{ github.repository }}"
          echo "Triggered by: ${{ github.event_name }}"
          echo "Reference: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
          echo "Build timestamp: $(date)"
          echo "================================================"   
  
  release:
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
