name: Publish GitHub Release Notes to website repo to create blog post

on:
  release:
    types: [released]

jobs:
  publish-release-notes:
    runs-on: ubuntu-latest
    # if: ${{ github.event.release.prerelease == false }} 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: TeamAudio/techaudio-web
          ref: actions-v1
          fetch-depth: 0  # Fetch all history for accurate versioning
          token: ${{ secrets.PUBLISH_RELEASE_SERVICE_TOKEN}}
          path: techaudio-web

      - name: Call publish-release action
        uses: ./techaudio-web/.github/actions/publish-release
        with:
          project_id: reaspeech-lite
          project_name: ReaSpeech Lite
          project_repository: ${{ github.repository }}
          version_tag: ${{ github.event.release.tag_name || 'manual-test-tag' }}
          release_body: ${{ github.event.release.body }}
          service_token: ${{ secrets.PUBLISH_RELEASE_SERVICE_TOKEN }}

